name: Docker Image CI

on:
  push:
    branches: [ 'feature/*' ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag spring-boot-helloworld:0.0.1